name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ vars.APP_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy to Cloudflare
        uses: ./.github/actions/cloudflare-deploy
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          deploy_env: dev
