name: Deploy - prod

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ${{ vars.APP_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # This is required for cloudflare/wrangler-action to work
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: prod
