name: Deploy - prod

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ${{ vars.APP_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: prod
